---
title: "Survey data summary"
author: "EWilliams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#
Data_type <- c("SRVY")
Initials <- c("ELW")
#
#
knitr::opts_chunk$set(echo = TRUE)
#Load packages, install as needed
#if (!require("remotes")) install.packages("remotes")
if (!require("pacman")) {install.packages("pacman")}
pacman::p_load(plyr, tidyverse, #Df manipulation, 
               ggpubr, scales, lemon, ggnewscale, gt, #ploting, tables
               rstatix, broom, #Summary stats
               zoo, lubridate, forecast, #Dates and times
               readxl, #Reading excel files
               car, emmeans, multcomp, #Basic analyses
               lmPerm, stats, glmmTMB, AICcmodavg, DHARMa, performance,
               install = TRUE)

```

```{r Formatting, include=FALSE}
#
#
basetheme <- theme_bw()+
  theme(axis.title.x = element_text(size = 12, face = "bold", color = "black"), 
        axis.text.x = element_text(size = 11, margin = margin(t=0.5, l=0.5, r=0, b=0.15, unit = "cm")),
        axis.title.y = element_text(size = 12, face = "bold", color = "black"), 
        axis.text.y = element_text(size = 11, margin = margin(t=0, l=0.25, r=0, b=0, unit = "cm")),
        panel.grid = element_blank(), 
        panel.border = element_blank(), 
        axis.line = element_line(color = "black"),
        axis.ticks.length = unit(-0.15, "cm"))
#
#
```

```{r Load data files, include=FALSE}

## Trip Info data
Trip_raw <- read_excel("../Data/Raw data/TripInfo_raw_shared.xlsx", sheet = "TripInfo", #File name and sheet name
                        skip = 0, col_names = TRUE,  #How many rows to skip at top; are column names to be used
                        na = c("", "NULL", " ", "NAN", "na"), trim_ws = TRUE, #Values/placeholders for NAs; trim extra white space?
                        .name_repair = "unique") 
#
## Sample Event
Sample_raw <- read_excel("../Data/Raw data/SampleEvent_raw_shared.xlsx", sheet = "SampleEvent", #File name and sheet name
                       skip = 0, col_names = TRUE,  #How many rows to skip at top; are column names to be used
                       na = c("", "NULL", " ", "NAN", "na"), trim_ws = TRUE, #Values/placeholders for NAs; trim extra white space?
                       .name_repair = "unique") 
#
## Fixed Locations
FLID_raw <- read_excel("../Data/Raw data/FixedLocations_raw_shared.xlsx", sheet = "FixedLocations", #File name and sheet name
                       skip = 0, col_names = TRUE,  #How many rows to skip at top; are column names to be used
                       na = c("", "NULL", " ", "NAN", "na"), trim_ws = TRUE, #Values/placeholders for NAs; trim extra white space?
                       .name_repair = "unique") 
#
## Survey
Quads_raw <- read_excel("../Data/Raw data/SurveyQuadrat_raw.xlsx", sheet = "SurveyQuadrat_raw", #File name and sheet name
                       skip = 0, col_names = TRUE,  #How many rows to skip at top; are column names to be used
                       na = c("", "NULL", " ", "NAN", "na"), trim_ws = TRUE, #Values/placeholders for NAs; trim extra white space?
                       .name_repair = "unique") 
#
## Survey SHs
SHs_raw <- read_excel("../Data/Raw data/SurveySH_raw.xlsx", sheet = "SurveySH_raw", #File name and sheet name
                        skip = 0, col_names = TRUE,  #How many rows to skip at top; are column names to be used
                        na = c("", "NULL", " ", "NAN", "na"), trim_ws = TRUE, #Values/placeholders for NAs; trim extra white space?
                        .name_repair = "unique") 
#
```

```{r Data cleaning, include=FALSE}

## Station information
(FLIDs <- FLID_raw %>%
  # Limit to desired columns to add to other data
  dplyr::select("FLID" = FixedLocationID,
                Estuary,
                SectionName,
                StationNumber,
                StartDate,
                EndDate) %>%
   mutate(StartDate = as.Date(StartDate),
          EndDate = as.Date(EndDate),
          Lab = case_when(Estuary %in% c("AB", "SA") ~ "Eastpoint",
                          Estuary %in% c("SS", "WI") ~ "CrystalRiver",
                          TRUE ~ "StPete")))
#
#
#
## Survey counts
(Quads_c <- Quads_raw %>%
    # Correct column types
    mutate(across(c("NumLive", "NumDead", "TotalVolume", "TotalWeight", "NumLegal"), as.numeric)) %>%
    # Remove row number column
    dplyr::select(-`...1`)  %>%
    # Create Year, Month, Site, Station columns
    mutate(Date = as.Date(substr(SampleEventID, 8, 15), format = "%Y%m%d"),
           Year = substr(SampleEventID, 8, 11),
           Month = substr(SampleEventID, 12, 13),
           Estuary = substr(SampleEventID, 1, 2),
           FLID = substr(SampleEventID, 19, 22),
           Season = ifelse(as.numeric(Month) < 4, "Spring", 
                         ifelse(as.numeric(Month) > 9, "Winter", 
                                ifelse(as.numeric(Month) > 3 & as.numeric(Month) < 7, "Summer", "Fall")))) %>%
    # Calculate total live/dead per m2. NOTE: 2005-2007 used 1m2, 2008+ used 1/4m2
    mutate(TotalLive = as.numeric(case_when(Year == "2005" | Year == "2006" | Year == "2007" ~ NumLive, TRUE ~ NumLive*4)),
           TotalDead = as.numeric(case_when(Year == "2005" | Year == "2006" | Year == "2007" ~ NumDead, TRUE ~ NumDead*4))) %>%
    #Add DeadRatio 
    mutate(Total = NumLive+NumDead,
           DeadRatio = as.numeric(case_when(Total == 0 ~ 0, TRUE ~ NumDead/Total))) %>%
    # Filter to Spring and Fall surveys
    filter(Season == "Spring" | Season == "Fall") %>%
    # Column types
    mutate(across(c("Year", "Month", "Estuary", "QuadratNumber", "Season"), as.factor)) %>% 
    # Reorganize columns
    dplyr::select(Date, Year, Month, Season, Estuary, FLID, TotalLive, TotalDead, everything()))
#
# Add FLID info to Quads
(Quads_df <- left_join(Quads_c, 
                      FLIDs))

```

## Background
Survey data from Spring and Fall surveys is included in comparisons.

```{r Estuary annual summary, echo = FALSE}
suppressMessages(Annual_summ <- Quads_df %>%
                   # Group by all columns needed in data output
                   group_by(Lab, Year, Estuary) %>%
                   summarise(Samples = n(),
                             meanLive = mean(TotalLive, na.rm = TRUE),
                             sdLive = sd(TotalLive, na.rm = TRUE),
                             seLive   = sdLive / sqrt(n()),
                             minLive = min(TotalLive, na.rm = TRUE),
                             maxLive = max(TotalLive, na.rm = TRUE),
                             meanDead = mean(TotalDead, na.rm = TRUE),
                             minDead = min(TotalDead, na.rm = TRUE),
                             maxDead = max(TotalDead, na.rm = TRUE),
                             meanDeadRatio = mean(DeadRatio, na.rm = TRUE),
                             minDeadRatio = min(DeadRatio, na.rm = TRUE),
                             maxDeadRatio = max(DeadRatio, na.rm = TRUE)) %>%
                   filter(Estuary != "_0")
)
#
paste("List of sites included:")
unique(Annual_summ$Estuary)
#
#
```

## Mean annual live density 

```{r plots, echo=FALSE}
for(lab in unique(Annual_summ$Lab)) {

  cat("# **", lab, "**\n\n")  # Lab-level header
  
  # Summarized data
  lab_data <- Annual_summ %>%
    filter(Lab == lab)
  
  for(i in unique(lab_data$Estuary)){
    
    # Filter data to specific estuary and determine years of data:
      #Original data
    model_data <- Quads_df %>% 
      filter(Estuary == i) %>%
      mutate(Year = as.factor(Year)) %>% 
      group_by(Estuary, SectionName, Year) %>%
       summarise(MeanLive = mean(TotalLive, na.rm =T),
                 .groups = "drop") %>%
      droplevels()
    
    # Safety check: skip empty datasets
    if(nrow(model_data) == 0){
      cat("No model data available for", i, "\n\n")
      next
    }
    
      #Summarized data
    filtered <- lab_data %>% filter(Estuary == i) %>% droplevels()
    years <- paste(sort(unique(filtered$Year)), collapse = ", ")
    #
    cat("### Survey data for", i, "\n")
    cat("Years sampled:", years, "\n\n")
    #
    # Assess change over time
    if(dplyr::n_distinct(model_data$Year) > 1){
      
      set.seed(54321)
      Ann_model <- suppressWarnings(glmmTMB::glmmTMB(MeanLive ~ as.numeric(Year) + (1|SectionName), family = nbinom2, data = model_data))
      Ann_model2 <- suppressWarnings(glmmTMB::glmmTMB(MeanLive ~ Year + (1|SectionName), family = nbinom2, data = model_data))
      
       if(!is.null(Ann_model)){
         Ann_model_tab <- car::Anova(Ann_model, type = 3) %>%
           broom::tidy() %>% 
           as.data.frame() %>%
           mutate(statistic = round(statistic, 3),
                  p.value = round(p.value, 3))
         cat("\nAnnual comparisons:\n")
          print(Ann_model_tab)
          #
          
          Ann_cld <- suppressMessages(suppressWarnings(left_join(filtered, 
                               multcomp::cld(
            emmeans(Ann_model2, ~ Year, type = "response"),
            Letters = letters, adjust = "sidak") %>%
            as.data.frame() %>%
            rename(Group = .group) %>%
            mutate(Group = stringr::str_trim(Group)) %>%
              dplyr::select(Year, Group)))) 
          #
          p <- Ann_cld %>%
        ggplot(aes(Year, meanLive, fill = Group))+
        geom_bar(stat = "identity")+
        geom_errorbar(aes(ymin = meanLive, ymax = meanLive + seLive), width = 0.25)+
        ggtitle(i) +
        scale_x_discrete(expand = c(0.05,0.1))+
        scale_y_continuous("Average live oysters per m2", expand = expansion(mult = c(0,0.05)))+
        scale_fill_viridis_d()+
        basetheme + 
        theme(axis.text.x = element_text(angle = 45))
          #
         }
      } else {
        cat("Only one year of data avaiable.\n\n")
        
         p <- filtered %>%
        ggplot(aes(Year, meanLive))+
        geom_bar(stat = "identity")+
        geom_errorbar(aes(ymin = meanLive, ymax = meanLive + seLive), width = 0.25)+
        ggtitle(i) +
        scale_x_discrete(expand = c(0.05,0.1))+
        scale_y_continuous("Average live oysters per m2", expand = expansion(mult = c(0,0.05)))+
        basetheme + 
        theme(axis.text.x = element_text(angle = 45))
      }
    cat("\nAnnual means:\n")
    print(filtered %>% ungroup() %>% dplyr::select(Year, meanLive, seLive) %>% as.data.frame())
    cat("\n\n")
    print(p)
  }
}
#
#
```

